### ISSUE TITLE
[Bug] Newsletter page is broken.

### ISSUE THREAD

**Issue by c-edw** [libra/website#16]
# 🐛 Bug

## Steps to reproduce
- Visit https://developers.libra.org/newsletter_form
- Observe the message below (even with adblocker disabled, and after a page refresh)

![image](https://user-images.githubusercontent.com/38229097/59718035-225b0300-9211-11e9-8685-5c1b24d097b7.png)

## Expected Behavior
The message should not appear, *even with an adblocker enabled*.

## System information
Firefox, Chromium. Browser doesn't appear to affect anything here.

**Comment by gc3** [comment]
Thanks so much for finding this issue! We are fixing this as soon as possible.

**Comment by Zero-1729** [comment]
Just visited [https://developers.libra.org/newsletter_form](https://developers.libra.org/newsletter_form) on Brave, it seems it has been fixed.

I am currently seeing this

![Screen Shot](https://user-images.githubusercontent.com/23586626/59977107-2f874180-95c5-11e9-9213-d231cab6a113.png)

**Comment by ericnakagawa** [comment]
Website deployed with update.
