### ISSUE TITLE
[Bug] Search input field functionality is broken

### ISSUE THREAD

**Issue by ltfschoen** [libra/website#20]
# 🐛 Bug

## Steps to reproduce

* Go to https://developers.libra.org/
* Find the search icon at the top right of the webpage (where there is a white magnifying glass on a purple background and where the placeholder shown is "Search")
* Click the input field, enter your search criteria, press Enter

**Error message or problem**

* No search is performed
* No errors are observed in the browser inspectors console tab
* No network requests are shown in the browser inspectors network tab

## Expected Behavior

* Entering search criteria into the search input field should perform a search of the website 

## System information

Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by gc3** [comment]
Thank you so much for reporting this! We will fix it as soon as possible.

**Comment by gc3** [comment]
Fixed ! 

https://github.com/libra/website/commit/d67aaab4a866ec907aafb1c383362d214af406d1

**Comment by rxu18** [comment]
Has the fix been committed? Issue seems to persist.

Reproduced on Chrome, Firefox and Edge.

**Comment by gc3** [comment]
Committed but not pushed. Sorry for the delay!
