### ISSUE TITLE
[Bug] Broken link to Move IR

### ISSUE THREAD

**Issue by isdotjim** [libra/website#42]
# 🐛 Bug

https://developers.libra.org/docs/crates/move-language#exploring-move-ir

The most complete documentation of the Move IR syntax is the **grammar**. You can also take a look at the **parser for the Move IR**.

https://github.com/libra/libra/blob/master/language/compiler/src/parser/mod.rs
https://github.com/libra/libra/blob/master/language/compiler/src/parser/syntax.lalrpop

**Comment by huitseeker** [comment]
https://github.com/libra/libra/pull/241
